export const BANH_MEMU = [
  {
    id: 1,
    name: 'Bánh Su Kem',
    icon: 'cake',
    image: 'https://i.ytimg.com/vi/qa0eK9CdvUE/maxresdefault.jpg',
    price: 1200,
    describle: 'Bánh Bao Có Vỏ Bánh giòn Dai Cùng Nhân Thịt Xá Xíu Mặn Ngọt ! ',
    soluong: 50,
    status: false,
  },
  {
    id: 2,
    name: 'Bánh Trứng Cuốc',
    icon: 'cake',
    image:
      'https://cdn.tgdd.vn/Files/2020/05/21/1257337/cach-lam-banh-bao-nuong-ngan-lop-nhan-man-thom-ngo-760x367.png',
    price: 1200,
    describle: 'Bánh Bao Có Vỏ Bánh giòn Dai Cùng Nhân Thịt Xá Xíu Mặn Ngọt ! ',
    soluong: 50,
    status: true,
  },
  {
    id: 3,
    name: 'Bánh Dừa Nướng',
    icon: 'cake',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTJyvJr9NRa7fhNIdULqLzWF9zN5hRnS2T5Jw&usqp=CAU',
    price: 1200,
    describle: 'Bánh Bao Có Vỏ Bánh giòn Dai Cùng Nhân Thịt Xá Xíu Mặn Ngọt ! ',
    soluong: 50,
    status: true,
  },
  {
    id: 4,
    name: 'Bánh Xúc Xích',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTJyvJr9NRa7fhNIdULqLzWF9zN5hRnS2T5Jw&usqp=CAU',
    price: 1200,
    icon: 'cake',
    describle: 'Bánh Bao Có Vỏ Bánh giòn Dai Cùng Nhân Thịt Xá Xíu Mặn Ngọt ! ',
    soluong: 50,
    status: true,
  },
  {
    id: 5,
    name: 'Bánh Sò Nướng',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTKdhklpvpWZ1CEKFMWcmeRaEZWAzoNrd15yQ&usqp=CAU',
    price: 1200,
    icon: 'cake',
    describle: 'Bánh Bao Có Vỏ Bánh giòn Dai Cùng Nhân Thịt Xá Xíu Mặn Ngọt ! ',
    soluong: 50,
    status: true,
  },
  {
    id: 6,
    name: 'Bánh Sò Hấp',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTJyvJr9NRa7fhNIdULqLzWF9zN5hRnS2T5Jw&usqp=CAU',
    price: 1200,
    icon: 'cake',
    describle: 'Bánh Bao Có Vỏ Bánh giòn Dai Cùng Nhân Thịt Xá Xíu Mặn Ngọt ! ',
    soluong: 50,
    status: true,
  },
  {
    id: 7,
    name: 'Bánh Dứa Nhân Dừa',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQLuQBgMUn96dts8VlTZNLO6-rxVSYXKhF5Ag&usqp=CAU',
    price: 1200,
    icon: 'cake',
    describle: 'Bánh Bao Có Vỏ Bánh giòn Dai Cùng Nhân Thịt Xá Xíu Mặn Ngọt ! ',
    soluong: 50,
    status: true,
  },
  {
    id: 8,
    name: 'Bánh Dứa Đậu Xanh',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQhI0eRKSQf24_qj0D6FLUxQI_pq487PMr2LQ&usqp=CAU',
    price: 1200,
    icon: 'cake',
    describle: 'Bánh Bao Có Vỏ Bánh giòn Dai Cùng Nhân Thịt Xá Xíu Mặn Ngọt ! ',
    soluong: 50,
    status: true,
  },
  {
    id: 9,
    name: 'Bánh Dứa Đậu Xanh',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQhI0eRKSQf24_qj0D6FLUxQI_pq487PMr2LQ&usqp=CAU',
    price: 1200,
    icon: 'cake',
    describle: 'Bánh Bao Có Vỏ Bánh giòn Dai Cùng Nhân Thịt Xá Xíu Mặn Ngọt ! ',
    soluong: 50,
    status: true,
  },
];
